//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndianaFord.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndianaFord.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne skarby Indiany Forda.
        /// </summary>
        internal static string AktualneSkarby {
            get {
                return ResourceManager.GetString("AktualneSkarby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualne złoto Indiany Forda.
        /// </summary>
        internal static string AktualneZłoto {
            get {
                return ResourceManager.GetString("AktualneZłoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualny ekwipunek Indiany Forda.
        /// </summary>
        internal static string AktualnyEkwipunek {
            get {
                return ResourceManager.GetString("AktualnyEkwipunek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot został dodany do ekwipunku.
        /// </summary>
        internal static string DodanieEkwipunku {
            get {
                return ResourceManager.GetString("DodanieEkwipunku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skarb został dodany do ekwipunku.
        /// </summary>
        internal static string DodanieSkarbu {
            get {
                return ResourceManager.GetString("DodanieSkarbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koniec Gry. Indiana Jones uzyskał .
        /// </summary>
        internal static string KoniecGry {
            get {
                return ResourceManager.GetString("KoniecGry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieudane przejście przeszkody.
        /// </summary>
        internal static string NieudanePrzejsciePrzeszkody {
            get {
                return ResourceManager.GetString("NieudanePrzejsciePrzeszkody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieudana próba zdobycia skarbu , nie posiadasz odpowiedniego przedmiotu..
        /// </summary>
        internal static string NieudaneZdobycieSkarbu {
            get {
                return ResourceManager.GetString("NieudaneZdobycieSkarbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udało sie otworzyć skrzynię.
        /// </summary>
        internal static string OtworzenieSkrzyni {
            get {
                return ResourceManager.GetString("OtworzenieSkrzyni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Udało sie przejść przeszkodę.
        /// </summary>
        internal static string PrzejsciePrzeszkody {
            get {
                return ResourceManager.GetString("PrzejsciePrzeszkody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indiana Ford poruszył się.
        /// </summary>
        internal static string Ruch {
            get {
                return ResourceManager.GetString("Ruch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skrzynia jest zamknięta,  nie została jeszcze otworzona.
        /// </summary>
        internal static string SkrzyniaZamknieta {
            get {
                return ResourceManager.GetString("SkrzyniaZamknieta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Przedmiot został usuniety z ekwipunku.
        /// </summary>
        internal static string UsuniecieEkwipunku {
            get {
                return ResourceManager.GetString("UsuniecieEkwipunku", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skarb został usuniety z ekwipunku.
        /// </summary>
        internal static string UsuniecieSkarbu {
            get {
                return ResourceManager.GetString("UsuniecieSkarbu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulacje , udało Ci sie zdobyć krzystałową czaszkę.
        /// </summary>
        internal static string ZdobycieKryształowejCzaszki {
            get {
                return ResourceManager.GetString("ZdobycieKryształowejCzaszki", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratulacje , udało Ci sie zdobyć skarb.
        /// </summary>
        internal static string ZdobycieSkarbu {
            get {
                return ResourceManager.GetString("ZdobycieSkarbu", resourceCulture);
            }
        }
    }
}
